{{- if gt (len .Values.nginxGateway.watchNamespaces) 0 }}
  {{- $watchNamespaces := .Values.nginxGateway.watchNamespaces }}
  {{- if not (has .Release.Namespace $watchNamespaces) }}
    {{- $watchNamespaces = append $watchNamespaces .Release.Namespace }}
  {{- end }}
  {{- range $ns := $watchNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nginx-gateway.fullname" $ }}
  namespace: {{ $ns }}
  labels:
  {{- include "nginx-gateway.labels" $ | nindent 4 }}
rules:
{{ include "rbac.namespacedRules" $ }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nginx-gateway.fullname" $ }}
  namespace: {{ $ns }}
  labels:
    {{- include "nginx-gateway.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nginx-gateway.fullname" $ }}
subjects:
- kind: ServiceAccount
  name: {{ include "nginx-gateway.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nginx-gateway.fullname" . }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
rules:
{{ include "rbac.clusterRules" . }}
{{- if eq (len .Values.nginxGateway.watchNamespaces) 0 }}
{{ include "rbac.namespacedRules" . }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nginx-gateway.fullname" . }}
  labels:
  {{- include "nginx-gateway.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nginx-gateway.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "nginx-gateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
