name: Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "0.0.0"

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Branch
        id: branch
        run: |
          version=${{ github.event.inputs.version }}
          version=${version%.*}
          echo "branch=release-$version" >> $GITHUB_OUTPUT

      - name: Checkout Repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ steps.branch.outputs.branch }}

      - name: Get Release Notes
        id: notes
        uses: lucacome/draft-release@0ebb400b90474a1b791602046abf8394e9f5402d # v2.0.2
        with:
          config-path: .github/release-notes.yml
          dry-run: true

      - name: Vars
        id: vars
        run: |
          # TODO(lucacome): improve this and maybe use appVersion instead of version if we switch to tags
          echo "current_version=$(yq '.version' <charts/nginx-gateway-fabric/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@f1069b438f125e5395d84d1c6fd3b559a7880cb5 # 3.0.5
        with:
          find: "edge"
          replace: ${{ inputs.version }}
          include: "charts/nginx-gateway-fabric/*.yaml"
          regex: false

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@f1069b438f125e5395d84d1c6fd3b559a7880cb5 # 3.0.5
        with:
          find: ${{ steps.vars.outputs.current_version }}
          replace: ${{ inputs.version }}
          include: "charts/nginx-gateway-fabric/*.yaml"
          regex: false

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@f1069b438f125e5395d84d1c6fd3b559a7880cb5 # 3.0.5
        with:
          find: ": Always"
          replace: ": IfNotPresent"
          include: "charts/nginx-gateway-fabric/*.yaml"
          regex: false

      - name: Generate files and changelog
        run: |
          sed -i -e "s/v${{ steps.vars.outputs.current_version }}/v${{ inputs.version }}/g" README.md
          sed -i -e "s/\[${{ steps.vars.outputs.current_version }}\]/\[${{ inputs.version }}\]/g" README.md
          sed -i -e "s/VERSION = edge/VERSION = ${{ inputs.version }}/g" Makefile
          sed -i "6r .github/CHANGELOG_TEMPLATE.md" CHANGELOG.md
          sed -i -e "s/%%VERSION%%/${{ inputs.version }}/g" CHANGELOG.md
          sed -i "8a ${{ join(fromJson(steps.notes.outputs.release-sections).release-notes, '\n') }}\n" CHANGELOG.md
          make generate-all

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Release ${{ inputs.version }}
          title: Release ${{ inputs.version }}
          draft: true
          delete-branch: true
          branch: docs/release-${{ inputs.version }}
          author: nginx-bot <integrations@nginx.com>
          committer: nginx-bot <integrations@nginx.com>
          body: |
            This automated PR updates all the necessary files for ${{ inputs.version }} release.
